name: Assign reviewers based on assignees
on:
  pull_request:
    types: [assigned, unassigned]
    branches:
      - master

jobs:
  assignee_to_reviewer:
    runs-on: macos-latest
    steps:
      - name: Assignee to Reviewer
        uses: pullreminders/assignee-to-reviewer-action@v1.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
